apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: config-default
  namespace: imreddy-jupyter
spec:
  iap:
    enabled: true
    oauthclientCredentials:
      secretName: my-secret
